spring:
  application:
    name: sh-auth-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:mysql://${ENV_DB_HOST:localhost}:${ENV_DB_PORT:3306}/${ENV_DB_NAME:sh_auth}
    username: ${ENV_DB_USER:springstudent}
    password: ${ENV_DB_PASS:springstudent}

server:
  port: ${ENV_SERVER_PORT:8080}